//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_enemyskeletor_H
#define METASPRITE_enemyskeletor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo enemyskeletor;

#endif
