//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_orpheus_H
#define METASPRITE_orpheus_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo orpheus;

#endif
