/*

 INTRO4T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 143

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __intro4t_h_INCLUDE
#define __intro4t_h_INCLUDE

/* Bank of tiles. */
#define intro4tBank 0

/* Super Gameboy palette 0 */
#define intro4tSGBPal0c0 0
#define intro4tSGBPal0c1 0
#define intro4tSGBPal0c2 0
#define intro4tSGBPal0c3 0

/* Super Gameboy palette 1 */
#define intro4tSGBPal1c0 6076
#define intro4tSGBPal1c1 8935
#define intro4tSGBPal1c2 6596
#define intro4tSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define intro4tSGBPal2c0 6076
#define intro4tSGBPal2c1 8935
#define intro4tSGBPal2c2 6596
#define intro4tSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define intro4tSGBPal3c0 6076
#define intro4tSGBPal3c1 8935
#define intro4tSGBPal3c2 6596
#define intro4tSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define intro4tCGBPal0c0 28638
#define intro4tCGBPal0c1 14175
#define intro4tCGBPal0c2 25888
#define intro4tCGBPal0c3 0

/* Gameboy Color palette 1 */
#define intro4tCGBPal1c0 28638
#define intro4tCGBPal1c1 14175
#define intro4tCGBPal1c2 649
#define intro4tCGBPal1c3 0

/* Gameboy Color palette 2 */
#define intro4tCGBPal2c0 28638
#define intro4tCGBPal2c1 14175
#define intro4tCGBPal2c2 317
#define intro4tCGBPal2c3 0

/* Gameboy Color palette 3 */
#define intro4tCGBPal3c0 6076
#define intro4tCGBPal3c1 8935
#define intro4tCGBPal3c2 6596
#define intro4tCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define intro4tCGBPal4c0 6076
#define intro4tCGBPal4c1 8935
#define intro4tCGBPal4c2 6596
#define intro4tCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define intro4tCGBPal5c0 6076
#define intro4tCGBPal5c1 8935
#define intro4tCGBPal5c2 6596
#define intro4tCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define intro4tCGBPal6c0 6076
#define intro4tCGBPal6c1 8935
#define intro4tCGBPal6c2 6596
#define intro4tCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define intro4tCGBPal7c0 6076
#define intro4tCGBPal7c1 8935
#define intro4tCGBPal7c2 6596
#define intro4tCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char intro4t[];

#endif

/* End of INTRO4T.H */
