/*

 MAPBOSSMINOST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapbossminost_h_INCLUDE
#define __mapbossminost_h_INCLUDE

/* Bank of tiles. */
#define mapbossminostBank 0

/* Super Gameboy palette 0 */
#define mapbossminostSGBPal0c0 0
#define mapbossminostSGBPal0c1 0
#define mapbossminostSGBPal0c2 0
#define mapbossminostSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapbossminostSGBPal1c0 6076
#define mapbossminostSGBPal1c1 8935
#define mapbossminostSGBPal1c2 6596
#define mapbossminostSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapbossminostSGBPal2c0 6076
#define mapbossminostSGBPal2c1 8935
#define mapbossminostSGBPal2c2 6596
#define mapbossminostSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapbossminostSGBPal3c0 6076
#define mapbossminostSGBPal3c1 8935
#define mapbossminostSGBPal3c2 6596
#define mapbossminostSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapbossminostCGBPal0c0 28539
#define mapbossminostCGBPal0c1 18302
#define mapbossminostCGBPal0c2 32269
#define mapbossminostCGBPal0c3 0

/* Gameboy Color palette 1 */
#define mapbossminostCGBPal1c0 31504
#define mapbossminostCGBPal1c1 18302
#define mapbossminostCGBPal1c2 32424
#define mapbossminostCGBPal1c3 26638

/* Gameboy Color palette 2 */
#define mapbossminostCGBPal2c0 32767
#define mapbossminostCGBPal2c1 21310
#define mapbossminostCGBPal2c2 282
#define mapbossminostCGBPal2c3 1130

/* Gameboy Color palette 3 */
#define mapbossminostCGBPal3c0 32767
#define mapbossminostCGBPal3c1 18302
#define mapbossminostCGBPal3c2 282
#define mapbossminostCGBPal3c3 0

/* Gameboy Color palette 4 */
#define mapbossminostCGBPal4c0 6076
#define mapbossminostCGBPal4c1 8935
#define mapbossminostCGBPal4c2 6596
#define mapbossminostCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapbossminostCGBPal5c0 6076
#define mapbossminostCGBPal5c1 8935
#define mapbossminostCGBPal5c2 6596
#define mapbossminostCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapbossminostCGBPal6c0 6076
#define mapbossminostCGBPal6c1 8935
#define mapbossminostCGBPal6c2 6596
#define mapbossminostCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapbossminostCGBPal7c0 6076
#define mapbossminostCGBPal7c1 8935
#define mapbossminostCGBPal7c2 6596
#define mapbossminostCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapbossminost[];

#endif

/* End of MAPBOSSMINOST.H */
