/*

 MAPBOSSHADEST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapbosshadest_h_INCLUDE
#define __mapbosshadest_h_INCLUDE

/* Bank of tiles. */
#define mapbosshadestBank 0

/* Super Gameboy palette 0 */
#define mapbosshadestSGBPal0c0 0
#define mapbosshadestSGBPal0c1 0
#define mapbosshadestSGBPal0c2 0
#define mapbosshadestSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapbosshadestSGBPal1c0 6076
#define mapbosshadestSGBPal1c1 8935
#define mapbosshadestSGBPal1c2 6596
#define mapbosshadestSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapbosshadestSGBPal2c0 6076
#define mapbosshadestSGBPal2c1 8935
#define mapbosshadestSGBPal2c2 6596
#define mapbosshadestSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapbosshadestSGBPal3c0 6076
#define mapbosshadestSGBPal3c1 8935
#define mapbosshadestSGBPal3c2 6596
#define mapbosshadestSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapbosshadestCGBPal0c0 28539
#define mapbosshadestCGBPal0c1 18302
#define mapbosshadestCGBPal0c2 32269
#define mapbosshadestCGBPal0c3 0

/* Gameboy Color palette 1 */
#define mapbosshadestCGBPal1c0 31504
#define mapbosshadestCGBPal1c1 18302
#define mapbosshadestCGBPal1c2 32424
#define mapbosshadestCGBPal1c3 26638

/* Gameboy Color palette 2 */
#define mapbosshadestCGBPal2c0 32767
#define mapbosshadestCGBPal2c1 18302
#define mapbosshadestCGBPal2c2 282
#define mapbosshadestCGBPal2c3 1130

/* Gameboy Color palette 3 */
#define mapbosshadestCGBPal3c0 32767
#define mapbosshadestCGBPal3c1 18302
#define mapbosshadestCGBPal3c2 282
#define mapbosshadestCGBPal3c3 0

/* Gameboy Color palette 4 */
#define mapbosshadestCGBPal4c0 28539
#define mapbosshadestCGBPal4c1 18302
#define mapbosshadestCGBPal4c2 20500
#define mapbosshadestCGBPal4c3 0

/* Gameboy Color palette 5 */
#define mapbosshadestCGBPal5c0 6076
#define mapbosshadestCGBPal5c1 8935
#define mapbosshadestCGBPal5c2 6596
#define mapbosshadestCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapbosshadestCGBPal6c0 6076
#define mapbosshadestCGBPal6c1 8935
#define mapbosshadestCGBPal6c2 6596
#define mapbosshadestCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapbosshadestCGBPal7c0 6076
#define mapbosshadestCGBPal7c1 8935
#define mapbosshadestCGBPal7c2 6596
#define mapbosshadestCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapbosshadest[];

#endif

/* End of MAPBOSSHADEST.H */
