/*

 MAPBOSSHADEST01.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapbosshadest01_h_INCLUDE
#define __mapbosshadest01_h_INCLUDE

/* Bank of tiles. */
#define mapbosshadest01Bank 0

/* Super Gameboy palette 0 */
#define mapbosshadest01SGBPal0c0 0
#define mapbosshadest01SGBPal0c1 0
#define mapbosshadest01SGBPal0c2 0
#define mapbosshadest01SGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapbosshadest01SGBPal1c0 6076
#define mapbosshadest01SGBPal1c1 8935
#define mapbosshadest01SGBPal1c2 6596
#define mapbosshadest01SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapbosshadest01SGBPal2c0 6076
#define mapbosshadest01SGBPal2c1 8935
#define mapbosshadest01SGBPal2c2 6596
#define mapbosshadest01SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapbosshadest01SGBPal3c0 6076
#define mapbosshadest01SGBPal3c1 8935
#define mapbosshadest01SGBPal3c2 6596
#define mapbosshadest01SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapbosshadest01CGBPal0c0 28539
#define mapbosshadest01CGBPal0c1 18302
#define mapbosshadest01CGBPal0c2 32269
#define mapbosshadest01CGBPal0c3 0

/* Gameboy Color palette 1 */
#define mapbosshadest01CGBPal1c0 31504
#define mapbosshadest01CGBPal1c1 18302
#define mapbosshadest01CGBPal1c2 32424
#define mapbosshadest01CGBPal1c3 26638

/* Gameboy Color palette 2 */
#define mapbosshadest01CGBPal2c0 32767
#define mapbosshadest01CGBPal2c1 18302
#define mapbosshadest01CGBPal2c2 282
#define mapbosshadest01CGBPal2c3 1130

/* Gameboy Color palette 3 */
#define mapbosshadest01CGBPal3c0 32767
#define mapbosshadest01CGBPal3c1 18302
#define mapbosshadest01CGBPal3c2 282
#define mapbosshadest01CGBPal3c3 0

/* Gameboy Color palette 4 */
#define mapbosshadest01CGBPal4c0 28539
#define mapbosshadest01CGBPal4c1 18302
#define mapbosshadest01CGBPal4c2 20500
#define mapbosshadest01CGBPal4c3 0

/* Gameboy Color palette 5 */
#define mapbosshadest01CGBPal5c0 6076
#define mapbosshadest01CGBPal5c1 8935
#define mapbosshadest01CGBPal5c2 6596
#define mapbosshadest01CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapbosshadest01CGBPal6c0 6076
#define mapbosshadest01CGBPal6c1 8935
#define mapbosshadest01CGBPal6c2 6596
#define mapbosshadest01CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapbosshadest01CGBPal7c0 6076
#define mapbosshadest01CGBPal7c1 8935
#define mapbosshadest01CGBPal7c2 6596
#define mapbosshadest01CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapbosshadest01[];

#endif

/* End of MAPBOSSHADEST01.H */
