/*

 MAPBOSSCERBERUST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapbosscerberust_h_INCLUDE
#define __mapbosscerberust_h_INCLUDE

/* Bank of tiles. */
#define mapbosscerberustBank 0

/* Super Gameboy palette 0 */
#define mapbosscerberustSGBPal0c0 0
#define mapbosscerberustSGBPal0c1 0
#define mapbosscerberustSGBPal0c2 0
#define mapbosscerberustSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapbosscerberustSGBPal1c0 6076
#define mapbosscerberustSGBPal1c1 8935
#define mapbosscerberustSGBPal1c2 6596
#define mapbosscerberustSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapbosscerberustSGBPal2c0 6076
#define mapbosscerberustSGBPal2c1 8935
#define mapbosscerberustSGBPal2c2 6596
#define mapbosscerberustSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapbosscerberustSGBPal3c0 6076
#define mapbosscerberustSGBPal3c1 8935
#define mapbosscerberustSGBPal3c2 6596
#define mapbosscerberustSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapbosscerberustCGBPal0c0 28539
#define mapbosscerberustCGBPal0c1 18302
#define mapbosscerberustCGBPal0c2 32269
#define mapbosscerberustCGBPal0c3 0

/* Gameboy Color palette 1 */
#define mapbosscerberustCGBPal1c0 31504
#define mapbosscerberustCGBPal1c1 18302
#define mapbosscerberustCGBPal1c2 32424
#define mapbosscerberustCGBPal1c3 26638

/* Gameboy Color palette 2 */
#define mapbosscerberustCGBPal2c0 32767
#define mapbosscerberustCGBPal2c1 21310
#define mapbosscerberustCGBPal2c2 282
#define mapbosscerberustCGBPal2c3 1130

/* Gameboy Color palette 3 */
#define mapbosscerberustCGBPal3c0 6076
#define mapbosscerberustCGBPal3c1 8935
#define mapbosscerberustCGBPal3c2 6596
#define mapbosscerberustCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mapbosscerberustCGBPal4c0 6076
#define mapbosscerberustCGBPal4c1 8935
#define mapbosscerberustCGBPal4c2 6596
#define mapbosscerberustCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapbosscerberustCGBPal5c0 6076
#define mapbosscerberustCGBPal5c1 8935
#define mapbosscerberustCGBPal5c2 6596
#define mapbosscerberustCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapbosscerberustCGBPal6c0 6076
#define mapbosscerberustCGBPal6c1 8935
#define mapbosscerberustCGBPal6c2 6596
#define mapbosscerberustCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapbosscerberustCGBPal7c0 6076
#define mapbosscerberustCGBPal7c1 8935
#define mapbosscerberustCGBPal7c2 6596
#define mapbosscerberustCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapbosscerberust[];

#endif

/* End of MAPBOSSCERBERUST.H */
