/*

 MAPBOSSMINOST04.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapbossminost04_h_INCLUDE
#define __mapbossminost04_h_INCLUDE

/* Bank of tiles. */
#define mapbossminost04Bank 0
/* Start of tile array. */
extern const unsigned char mapbossminost04[];

#endif

/* End of MAPBOSSMINOST04.H */
