/*

 MAPENDSCREENT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapendscreent_h_INCLUDE
#define __mapendscreent_h_INCLUDE

/* Bank of tiles. */
#define mapendscreentBank 0

/* Super Gameboy palette 0 */
#define mapendscreentSGBPal0c0 0
#define mapendscreentSGBPal0c1 0
#define mapendscreentSGBPal0c2 0
#define mapendscreentSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapendscreentSGBPal1c0 6076
#define mapendscreentSGBPal1c1 8935
#define mapendscreentSGBPal1c2 6596
#define mapendscreentSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapendscreentSGBPal2c0 6076
#define mapendscreentSGBPal2c1 8935
#define mapendscreentSGBPal2c2 6596
#define mapendscreentSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapendscreentSGBPal3c0 6076
#define mapendscreentSGBPal3c1 8935
#define mapendscreentSGBPal3c2 6596
#define mapendscreentSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapendscreentCGBPal0c0 20414
#define mapendscreentCGBPal0c1 8991
#define mapendscreentCGBPal0c2 246
#define mapendscreentCGBPal0c3 0

/* Gameboy Color palette 1 */
#define mapendscreentCGBPal1c0 6076
#define mapendscreentCGBPal1c1 8935
#define mapendscreentCGBPal1c2 6596
#define mapendscreentCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapendscreentCGBPal2c0 6076
#define mapendscreentCGBPal2c1 8935
#define mapendscreentCGBPal2c2 6596
#define mapendscreentCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define mapendscreentCGBPal3c0 6076
#define mapendscreentCGBPal3c1 8935
#define mapendscreentCGBPal3c2 6596
#define mapendscreentCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mapendscreentCGBPal4c0 6076
#define mapendscreentCGBPal4c1 8935
#define mapendscreentCGBPal4c2 6596
#define mapendscreentCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapendscreentCGBPal5c0 6076
#define mapendscreentCGBPal5c1 8935
#define mapendscreentCGBPal5c2 6596
#define mapendscreentCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapendscreentCGBPal6c0 6076
#define mapendscreentCGBPal6c1 8935
#define mapendscreentCGBPal6c2 6596
#define mapendscreentCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapendscreentCGBPal7c0 6076
#define mapendscreentCGBPal7c1 8935
#define mapendscreentCGBPal7c2 6596
#define mapendscreentCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapendscreent[];

#endif

/* End of MAPENDSCREENT.H */
