/*

 MAPHADES003ACHERONT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __maphades003acheront_h_INCLUDE
#define __maphades003acheront_h_INCLUDE

/* Bank of tiles. */
#define maphades003acherontBank 0

/* Super Gameboy palette 0 */
#define maphades003acherontSGBPal0c0 0
#define maphades003acherontSGBPal0c1 0
#define maphades003acherontSGBPal0c2 0
#define maphades003acherontSGBPal0c3 0

/* Super Gameboy palette 1 */
#define maphades003acherontSGBPal1c0 6076
#define maphades003acherontSGBPal1c1 8935
#define maphades003acherontSGBPal1c2 6596
#define maphades003acherontSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maphades003acherontSGBPal2c0 6076
#define maphades003acherontSGBPal2c1 8935
#define maphades003acherontSGBPal2c2 6596
#define maphades003acherontSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maphades003acherontSGBPal3c0 6076
#define maphades003acherontSGBPal3c1 8935
#define maphades003acherontSGBPal3c2 6596
#define maphades003acherontSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maphades003acherontCGBPal0c0 28539
#define maphades003acherontCGBPal0c1 18302
#define maphades003acherontCGBPal0c2 32269
#define maphades003acherontCGBPal0c3 0

/* Gameboy Color palette 1 */
#define maphades003acherontCGBPal1c0 31504
#define maphades003acherontCGBPal1c1 18302
#define maphades003acherontCGBPal1c2 32424
#define maphades003acherontCGBPal1c3 26638

/* Gameboy Color palette 2 */
#define maphades003acherontCGBPal2c0 32767
#define maphades003acherontCGBPal2c1 21310
#define maphades003acherontCGBPal2c2 282
#define maphades003acherontCGBPal2c3 1130

/* Gameboy Color palette 3 */
#define maphades003acherontCGBPal3c0 6076
#define maphades003acherontCGBPal3c1 8935
#define maphades003acherontCGBPal3c2 6596
#define maphades003acherontCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define maphades003acherontCGBPal4c0 6076
#define maphades003acherontCGBPal4c1 8935
#define maphades003acherontCGBPal4c2 6596
#define maphades003acherontCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maphades003acherontCGBPal5c0 6076
#define maphades003acherontCGBPal5c1 8935
#define maphades003acherontCGBPal5c2 6596
#define maphades003acherontCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maphades003acherontCGBPal6c0 6076
#define maphades003acherontCGBPal6c1 8935
#define maphades003acherontCGBPal6c2 6596
#define maphades003acherontCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maphades003acherontCGBPal7c0 6076
#define maphades003acherontCGBPal7c1 8935
#define maphades003acherontCGBPal7c2 6596
#define maphades003acherontCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char maphades003acheront[];

#endif

/* End of MAPHADES003ACHERONT.H */
