/*

 MAPHADES002T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __maphades002t_h_INCLUDE
#define __maphades002t_h_INCLUDE

/* Bank of tiles. */
#define maphades002tBank 0

/* Super Gameboy palette 0 */
#define maphades002tSGBPal0c0 0
#define maphades002tSGBPal0c1 0
#define maphades002tSGBPal0c2 0
#define maphades002tSGBPal0c3 0

/* Super Gameboy palette 1 */
#define maphades002tSGBPal1c0 6076
#define maphades002tSGBPal1c1 8935
#define maphades002tSGBPal1c2 6596
#define maphades002tSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maphades002tSGBPal2c0 6076
#define maphades002tSGBPal2c1 8935
#define maphades002tSGBPal2c2 6596
#define maphades002tSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maphades002tSGBPal3c0 6076
#define maphades002tSGBPal3c1 8935
#define maphades002tSGBPal3c2 6596
#define maphades002tSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maphades002tCGBPal0c0 28539
#define maphades002tCGBPal0c1 18302
#define maphades002tCGBPal0c2 32269
#define maphades002tCGBPal0c3 11489

/* Gameboy Color palette 1 */
#define maphades002tCGBPal1c0 6076
#define maphades002tCGBPal1c1 8935
#define maphades002tCGBPal1c2 6596
#define maphades002tCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define maphades002tCGBPal2c0 6076
#define maphades002tCGBPal2c1 8935
#define maphades002tCGBPal2c2 6596
#define maphades002tCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define maphades002tCGBPal3c0 6076
#define maphades002tCGBPal3c1 8935
#define maphades002tCGBPal3c2 6596
#define maphades002tCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define maphades002tCGBPal4c0 6076
#define maphades002tCGBPal4c1 8935
#define maphades002tCGBPal4c2 6596
#define maphades002tCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maphades002tCGBPal5c0 6076
#define maphades002tCGBPal5c1 8935
#define maphades002tCGBPal5c2 6596
#define maphades002tCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maphades002tCGBPal6c0 6076
#define maphades002tCGBPal6c1 8935
#define maphades002tCGBPal6c2 6596
#define maphades002tCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maphades002tCGBPal7c0 6076
#define maphades002tCGBPal7c1 8935
#define maphades002tCGBPal7c2 6596
#define maphades002tCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char maphades002t[];

#endif

/* End of MAPHADES002T.H */
