/*

 MAPHADES002TA5.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __maphades002ta5_h_INCLUDE
#define __maphades002ta5_h_INCLUDE

/* Bank of tiles. */
#define maphades002ta5Bank 0

/* Super Gameboy palette 0 */
#define maphades002ta5SGBPal0c0 0
#define maphades002ta5SGBPal0c1 0
#define maphades002ta5SGBPal0c2 0
#define maphades002ta5SGBPal0c3 0

/* Super Gameboy palette 1 */
#define maphades002ta5SGBPal1c0 6076
#define maphades002ta5SGBPal1c1 8935
#define maphades002ta5SGBPal1c2 6596
#define maphades002ta5SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maphades002ta5SGBPal2c0 6076
#define maphades002ta5SGBPal2c1 8935
#define maphades002ta5SGBPal2c2 6596
#define maphades002ta5SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maphades002ta5SGBPal3c0 6076
#define maphades002ta5SGBPal3c1 8935
#define maphades002ta5SGBPal3c2 6596
#define maphades002ta5SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maphades002ta5CGBPal0c0 28539
#define maphades002ta5CGBPal0c1 18302
#define maphades002ta5CGBPal0c2 32269
#define maphades002ta5CGBPal0c3 0

/* Gameboy Color palette 1 */
#define maphades002ta5CGBPal1c0 6076
#define maphades002ta5CGBPal1c1 8935
#define maphades002ta5CGBPal1c2 6596
#define maphades002ta5CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define maphades002ta5CGBPal2c0 6076
#define maphades002ta5CGBPal2c1 8935
#define maphades002ta5CGBPal2c2 6596
#define maphades002ta5CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define maphades002ta5CGBPal3c0 6076
#define maphades002ta5CGBPal3c1 8935
#define maphades002ta5CGBPal3c2 6596
#define maphades002ta5CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define maphades002ta5CGBPal4c0 6076
#define maphades002ta5CGBPal4c1 8935
#define maphades002ta5CGBPal4c2 6596
#define maphades002ta5CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maphades002ta5CGBPal5c0 6076
#define maphades002ta5CGBPal5c1 8935
#define maphades002ta5CGBPal5c2 6596
#define maphades002ta5CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maphades002ta5CGBPal6c0 6076
#define maphades002ta5CGBPal6c1 8935
#define maphades002ta5CGBPal6c2 6596
#define maphades002ta5CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maphades002ta5CGBPal7c0 6076
#define maphades002ta5CGBPal7c1 8935
#define maphades002ta5CGBPal7c2 6596
#define maphades002ta5CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char maphades002ta5[];

#endif

/* End of MAPHADES002TA5.H */
