/*

 MAPHADES003LETHET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __maphades003lethet_h_INCLUDE
#define __maphades003lethet_h_INCLUDE

/* Bank of tiles. */
#define maphades003lethetBank 0

/* Super Gameboy palette 0 */
#define maphades003lethetSGBPal0c0 0
#define maphades003lethetSGBPal0c1 0
#define maphades003lethetSGBPal0c2 0
#define maphades003lethetSGBPal0c3 0

/* Super Gameboy palette 1 */
#define maphades003lethetSGBPal1c0 6076
#define maphades003lethetSGBPal1c1 8935
#define maphades003lethetSGBPal1c2 6596
#define maphades003lethetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maphades003lethetSGBPal2c0 6076
#define maphades003lethetSGBPal2c1 8935
#define maphades003lethetSGBPal2c2 6596
#define maphades003lethetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maphades003lethetSGBPal3c0 6076
#define maphades003lethetSGBPal3c1 8935
#define maphades003lethetSGBPal3c2 6596
#define maphades003lethetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maphades003lethetCGBPal0c0 28539
#define maphades003lethetCGBPal0c1 31607
#define maphades003lethetCGBPal0c2 13761
#define maphades003lethetCGBPal0c3 0

/* Gameboy Color palette 1 */
#define maphades003lethetCGBPal1c0 31504
#define maphades003lethetCGBPal1c1 18302
#define maphades003lethetCGBPal1c2 32424
#define maphades003lethetCGBPal1c3 26638

/* Gameboy Color palette 2 */
#define maphades003lethetCGBPal2c0 32767
#define maphades003lethetCGBPal2c1 21310
#define maphades003lethetCGBPal2c2 282
#define maphades003lethetCGBPal2c3 1130

/* Gameboy Color palette 3 */
#define maphades003lethetCGBPal3c0 32767
#define maphades003lethetCGBPal3c1 18302
#define maphades003lethetCGBPal3c2 282
#define maphades003lethetCGBPal3c3 0

/* Gameboy Color palette 4 */
#define maphades003lethetCGBPal4c0 6076
#define maphades003lethetCGBPal4c1 8935
#define maphades003lethetCGBPal4c2 6596
#define maphades003lethetCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maphades003lethetCGBPal5c0 6076
#define maphades003lethetCGBPal5c1 8935
#define maphades003lethetCGBPal5c2 6596
#define maphades003lethetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maphades003lethetCGBPal6c0 6076
#define maphades003lethetCGBPal6c1 8935
#define maphades003lethetCGBPal6c2 6596
#define maphades003lethetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maphades003lethetCGBPal7c0 6076
#define maphades003lethetCGBPal7c1 8935
#define maphades003lethetCGBPal7c2 6596
#define maphades003lethetCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char maphades003lethet[];

#endif

/* End of MAPHADES003LETHET.H */
