typedef enum{
	FIRSTEVER,
    TUTORIAL_CARTEL,
    MISSING_LYRE,
    FOUND_LYRE,
    PUSH_BUTTON,
    PRESS_INTERACT,
    TUTORIAL_BLOCKS,
    TUTORIAL_PLAY,
    HADES_ENTRANCE,
    HADES_WELCOME
}WHOSTALKING;

