typedef enum{
	FIRSTEVER,
    TUTORIAL_CARTEL,
    MISSING_LYRE,
    FOUND_LYRE,
    PUSH_BUTTON,
    PRESS_INTERACT,
    TUTORIAL_BLOCKS,
    TUTORIAL_PLAY,
    HADES_ENTRANCE,
    HADES_WELCOME,
    HADES_MOVE_BLOCK,
    HADES_USE_KEY,
    HADES_KILL_ENEMY,
    HADES_DEATH,
    BOSS_CHARON_INTRO,
    BOSS_CHARON_BEATED,
    BOSS_CERBERUS_INTRO,
    BOSS_CERBERUS_BEATED
}WHOSTALKING;

